services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - private

  backend:
    build:
      args:
        - NODE_ENV=development
      context: postappback.ts
    command: npm run start:dev
    environment:
      - DATABASE_HOST=postgres
      - PORT=5000
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postapp
      - JWT_SECRET=secret
    ports:
      - "5000:5000"
    volumes:
      - ./postappback.ts/src:/home/node/app/src:ro
      - ./postappback.ts/package.json:/home/node/app/package.json
      - ./postappback.ts/package-lock.json:/home/node/app/package-lock.json
    networks:
      - public
      - private
    depends_on:
      - postgres

  frontend:
    build:
      context: postappfront.js
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./postappfront.js/src:/home/node/app/src
      - /home/node/app/node_modules
    networks:
      - public

networks:
  public:
  private:

volumes:
  pgdata:

