version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postapp-network

  backend:
    container_name: backend
    build:
      context: ./postappback.ts/
      dockerfile: ./Dockerfile.development
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./postappback.ts:/home/node/app
    networks:
      - postapp-network

  frontend:
    container_name: frontend
    build:
      context: ./postappfront.js/
      dockerfile: Dockerfile.development
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./postappfront.js:/home/node/app
    networks:
      - postapp-network

volumes:
  pgdata:

networks:
  postapp-network:
    driver: bridge
