name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar aplicação
        run: npm install

      - name: Executar teste unitário
        run: npm test

      - name: Subir containers
        run: |
          docker compose up -d --build

      - name: Verificar containers
        run: docker ps --filter "status=running"